Update agendamento.yml

diff --git a/.github/workflows/agendamento.yml b/.github/workflows/agendamento.yml
--- a/.github/workflows/agendamento.yml
+++ b/.github/workflows/agendamento.yml
@@ -29,7 +29,8 @@ jobs:
     - name: Executar Testes
       id: run_tests
       run: |
-        robot chatbot.robot && echo "test_status=passed" >> $GITHUB_OUTPUT || echo "test_status=failed" >> $GITHUB_OUTPUT
+        robot chatbot.robot && echo "test_status=passed" >> "$GITHUB_ENV" || echo "test_status=failed" >> "$GITHUB_ENV"
+        echo "test_status=${test_status}" >> "$GITHUB_OUTPUT"
     
     - name: Enviar e-mail com resultados
       if: ${{ steps.run_tests.outputs.test_status == 'failed' }}
