Update agendamento.yml

diff --git a/.github/workflows/agendamento.yml b/.github/workflows/agendamento.yml
--- a/.github/workflows/agendamento.yml
+++ b/.github/workflows/agendamento.yml
@@ -29,12 +29,10 @@ jobs:
     - name: Executar Testes
       id: run_tests
       run: |
-        robot --outputdir=resultados chatbot.robot || echo "::set-output name=test_status::failed"
-        if [ $? -eq 0 ]; then
-          echo "::set-output name=test_status::passed"
-        fi
+        robot chatbot.robot && echo "test_status=passed" >> $GITHUB_OUTPUT || echo "test_status=failed" >> $GITHUB_OUTPUT
     
     - name: Enviar e-mail com resultados
+      if: ${{ needs.run_tests.outputs.test_status == 'failed' }}
       uses: dawidd6/action-send-mail@v4
       with:
         server_address: smtp.gmail.com
@@ -42,7 +40,7 @@ jobs:
         username: ${{ secrets.EMAIL_USUARIO }}
         password: ${{ secrets.EMAIL_SENHA }}
         subject: "Resultados dos Testes"
-        body: "Os testes foram concluídos. Veja os arquivos anexos."
+        body: "Alguns testes falharam. Veja os arquivos anexos."
         to: ${{ secrets.EMAIL_DESTINATARIO }}
         from: ${{ secrets.EMAIL_USUARIO }}
         attachments: "resultados/output.xml, resultados/log.html, resultados/report.html"
